# Generated by Django 4.2.7 on 2026-09-17 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('sslcommerz', 'SSLCommerz'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cod', 'Cash on Delivery')], default='sslcommerz', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=200)),
                ('gateway_page_url', models.URLField(blank=True)),
                ('validation_id', models.CharField(blank=True, max_length=100)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('card_no', models.CharField(blank=True, max_length=50)),
                ('store_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('risk_title', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('ipn_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payment_pay_transac_f578fa_idx'), models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'), models.Index(fields=['-created_at'], name='payment_pay_created_c2327c_idx')],
            },
        ),
    ]
