# Generated by Django 5.0.6 on 2026-09-08 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='সঠিক মোবাইল নম্বর দিন। (যেমন: 01712345678 অথবা +8801712345678)', regex='^(?:(?:\\+?88)?01[3-9]\\d{8})$')]),
        ),
    ]
