# Generated by Django 6.1 on 2026-08-24 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_desserttype_alter_category_options_and_more'),
        ('products', '0002_remove_productimage_unique_product_image_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional delivery charge if any', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Dimensions (L x W x H) in cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Mark as best seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free_delivery',
            field=models.BooleanField(default=False, help_text='Free delivery available'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pre_order',
            field=models.BooleanField(default=False, help_text='Available for pre-order'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Regular selling price', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='serving_size',
            field=models.CharField(blank=True, help_text="Serving size (e.g., '6-8 people')", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.IntegerField(default=0, help_text='Shelf life in days'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for listing', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_options',
            field=models.JSONField(blank=True, default=dict, help_text='Available customization options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (if any)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Additional product images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Key features and highlights'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Product is visible in store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Available for order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='Can be customized'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on featured section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Mark as new arrival'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=5, help_text='Minimum stock alert level', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='preparation_time',
            field=models.IntegerField(default=0, help_text='Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Available quantity in stock', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Product specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Product video URL (YouTube/Vimeo)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in grams', max_digits=8),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
    ]
