# Generated by Django 5.0.6 on 2026-08-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_remove_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
