# Generated by Django 5.0.6 on 2026-08-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_highlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customization_options',
            field=models.JSONField(blank=True, default=dict, help_text='Available customization options', null=True),
        ),
    ]
